### ISSUE TITLE
DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead

### ISSUE THREAD

**Issue by tigt** [timse/name-all-modules-plugin#3]
Using `name-all-modules-plugin@1.0.1`:

```
(node:34067) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at NameAllModulesPlugin.apply (…/node_modules/name-all-modules-plugin/index.js:5:14)
    at webpack (…/node_modules/webpack/lib/webpack.js:47:13)
    at …/webpack/compiler.js:63:22
    at Promise._execute (…/node_modules/bluebird/js/release/debuggability.js:313:9)
    at Promise._resolveFromExecutor (…/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (…/node_modules/bluebird/js/release/promise.js:79:10)
    at compile (…/webpack/compiler.js:61:10)
    at module.exports.type (…/compile.js:18:10)
```

**Comment by tigt** [comment]
Looks like this will be fixed by the open Merge Request at #2
